
# Source: robot-shop/templates/cart-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: cart
---
# Source: robot-shop/templates/catalogue-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: catalogue
  name: catalogue
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: catalogue
---
# Source: robot-shop/templates/dispatch-service.yaml
# dispatch just listens to a message queue
# it does not expose any ports
apiVersion: v1
kind: Service
metadata:
  name: dispatch
  labels:
    service: dispatch
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: dispatch
---
# Source: robot-shop/templates/mongodb-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongodb
  name: mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
  selector:
    service: mongodb
---
# Source: robot-shop/templates/mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: mysql
  name: mysql
spec:
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
  selector:
    service: mysql
---
# Source: robot-shop/templates/payment-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    service: payment
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: payment
---
# Source: robot-shop/templates/rabbitmq-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    service: rabbitmq
spec:
  ports:
  - name: tcp-amqp
    port: 5672
    targetPort: 5672
  - name: http-management
    port: 15672
    targetPort: 15672
  - name: tcp-epmd
    port: 4369
    targetPort: 4369
  selector:
    service: rabbitmq
---
# Source: robot-shop/templates/ratings-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ratings
  labels:
    service: ratings
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    service: ratings
---
# Source: robot-shop/templates/redis-service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    service: redis
  name: redis
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    service: redis
---
# Source: robot-shop/templates/shipping-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    service: shipping
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: shipping
---
# Source: robot-shop/templates/user-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    service: user
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: user
---
# Source: robot-shop/templates/web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    service: web
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: web
  
  type: NodePort
